#! /usr/bin/env python

import rospy
from geometry_msgs.msg import Pose
from aubo_i5_planning_interface.planning_interface import PlanningInterface
import numpy as np

if __name__ == "__main__":
    rospy.init_node('move_line')

    # Create a planning interface object
    planning_interface = PlanningInterface()

    planning_interface.move_home(1, 1)

    # Create a pose object
    pose = Pose()
    pose.position.x = 0.5
    pose.position.y = 0.0
    pose.position.z = 0.5
    pose.orientation.x = 0
    pose.orientation.y = 0
    pose.orientation.z = 0
    pose.orientation.w = 1


    # planning_interface.move_line(pose, 1, 1)

    planning_interface.move_offset(
        np.array([-0.1, 0.0, -0.1, 1, 0, 0]),
        1, 
        1
    )