#! /usr/bin/env python

import rospy
from geometry_msgs.msg import Pose
from aubo_i5_planning_interface.planning_interface import PlanningInterface
import numpy as np

if __name__ == "__main__":
    rospy.init_node('move_line')

    # Create a planning interface object
    planning_interface = PlanningInterface()

    planning_interface.move_home(0.1, 0.1)

    planning_interface.move_offset(
        np.array([0, 0.0, 0, 0.5, 0, 0]),
        0.1, 
        0.1
    )